### PR TITLE
Upgrade to FVM 4.1.0

### PR DESCRIPTION
**Pull request by fridrik01**
Update to the most recent FVM version 4.1.0 to get the pluggable syscall features.

Fixes ENG-592.

### CODE REVIEW

**Review by aakoshh — APPROVED** [review]
LGTM!

**Review by raulk — APPROVED** [review]

**Comment by raulk** [comment]
Fixes ENG-592, I believe.

**Comment by raulk** [comment]
@fridrik01 Do we have an example for plugging in a custom syscall we can add to an `examples` directory here?

**Comment by fridrik01** [comment]
> @fridrik01 Do we have an example for plugging in a custom syscall we can add to an `examples` directory here?

I am working on a local branch, will push it later today

**Pull request merged**
