### PR TITLE
Change argument --subnet into --network for some of the ipc-cli subnet commands

### PR DESCRIPTION
**Pull request by mb1896**
Closes ENG-639

Please the discussion in linear ticket. Not sure what other subnet commands should adopt this change.

### CODE REVIEW

**Review by aakoshh — COMMENTED** [review]
I have always been confused by the `network`. I thought it can be `testnet` or `mainnet`, corresponding to the FVM `Network` type which is part of every `Address`. That's how it's used in the [fendermint CLI](https://github.com/consensus-shipyard/ipc/blob/316c97f69326631640f4ef7ba1945845c9036d27/fendermint/app/options/src/lib.rs#L44-L46)

I was hoping that all remaining occurrence of `network` in the contracts can be replaced by `subnet` actually. When it's a `SubnetID`, why not call a spade a spade?

**Comment by raulk** [comment]
@aakoshh there are 3 CLI commands being affected here:
- list subnets: more appropriate to call this flag `--parent`.
- RPC and chain ID query: these work for any network including the root, so `--subnet` is confusing and `--network` is more accurate IMO.

> I thought it can be testnet or mainnet, corresponding to the FVM Network type which is part of every Address. 

That should've really been called "network type" :-/

**Comment by mb1896** [comment]
@raulk Updated argument names as you mentioned. Does it look good to you now?

**Review by maciejwitowski — APPROVED** [review]

**Comment by maciejwitowski** [comment]
LGTM, merging not to block on @raulk  confirmation.

**Pull request merged**
