### PR TITLE
docs: move docs into monorepo

### PR DESCRIPTION
**Pull request by maciejwitowski**
At the moment, IPC docs are in the separate repo https://github.com/consensus-shipyard/docs
We want to simplify them by adding to this repo. Since in this repo `docs` folder already exists, they were put in `docs-gitbook`. The structure and naming of docs can be easily updated later.

Next, the migrated docs are used to render [the gitbook page](https://app.gitbook.com/o/DdhSSU8GveMWTVvBCegp/s/QWdqoo7LRP3OJYrMUo4I/overview/readme). I created this separate gitbook space for the purpose of checking. It will replace the main one once this PR is merged.

### CODE REVIEW

**Review by raulk — COMMENTED** [review]
Let's keep the images out of this repo to avoid bloating `git clone`s. If they were light design/architecture diagrams, I wouldn't mind hosting them here. But not worth it for unoptimized tutorial screenshots.

I'd suggest the following:

1. Keep media assets in the original docs repo, and embed them in the Markdowns using a GitHub URL.
2. Rename the images to self-descriptive names. Right now we have series of `metamask (1).png`, `metamask (2).png`... files.

**Comment by maciejwitowski** [comment]
@raulk Not bloating the repo makes sense. 
IIUC `git clone` will still be bloated if I just add a commit which removes `assets` folder from this repo and changes the links, correct? Does it mean I should copy folders/files without migrating the whole history?

**Comment by raulk** [comment]
@maciejwitowski it won't because we'll be squashing this PR in. You can migrate the assets by adding a commit to this PR.

**Comment by maciejwitowski** [comment]
@raulk Please check again. The docs website is already running from this branch https://docs.ipc.space/ 
Had to clean all these files in the docs repo, since they were added by gitbook via drag & drop and most of them were not referenced anywhere.

**Comment by maciejwitowski** [comment]
After this branch is merged I'm gonna switch docs website to use `main`.

**Review by raulk — COMMENTED** [review]
This looks fine as a starting point, even though the content needs significant revision. 
Just one question before I merge this: how does editing via the GitBook web interface work in this case?

We absolutely don't want (a) the GitBook bot committing directly to this repo, or (b) the GitBook bot to appear as a Git author anywhere.

**Pull request merged**
