### PR TITLE
Bugfix for hardhat incorrectly assuming that IPC is a legacy network

### PR DESCRIPTION
**Pull request by snissn**
Hardhat queries eth_feeHistory to construct its transaction and understand what gas format to use. Hardhat assumes that baseFeePerGas returned from this endpoint has an array length of 2 and ends up accidentally sending a malformed legacy transaction.

```

 mikeseiler@Mikes-MacBook-Air ipc-hardhat-test % npx hardhat --network local run scripts/deploy.js
 response {
   baseFeePerGas: [ '0x3e8' ],
   gasUsedRatio: [ 0 ],
   oldestBlock: '0x21287',
   reward: [ [ '0x0' ] ]
 }

 mikeseiler@Mikes-MacBook-Air ipc-hardhat-test % npx hardhat --network ganache  run scripts/deploy.js
 response {
   oldestBlock: '0x9',
   baseFeePerGas: [ '0x123d6551', '0x1002692e' ],
   gasUsedRatio: [ 0.0108704 ],
   reward: [ [ '0x4d84ee9' ] ]
 }

```
in hardhat -  [internal/core/providers/gas-provider.js](https://github.com/NomicFoundation/hardhat/blob/b626dc15b047773603964a66f7efa9982d188bda/packages/hardhat-core/src/internal/core/providers/gas-providers.ts#L290) this is where they create the error. 

Attached in this PR is code that simply doubles the array if it has a length of 1.

Related issue https://github.com/consensus-shipyard/ipc/issues/598

### CODE REVIEW

**Comment by aakoshh** [comment]
Strange, the code you link to shows that they are asking for 1 block in the results, yet they expect 2 items. 

Since you are touching that part of the code, could you please move [this statement](https://github.com/consensus-shipyard/ipc/blob/904705346b7788e79920526c95c0e62bee5869a3/fendermint/eth/api/src/apis/eth.rs#L277) inside the `if` above? That is, if there is no result for the latest block, we should not decrement the block count. 

It wouldn't help with this issue, but I think it would be possible to get 0 results even if somebody asks for 1.

**Comment by snissn** [comment]
I have been able to test this code change can confirm that it enables hardhat to properly connect with fendermint eth

**Comment by aakoshh** [comment]
Look, there is some [special casing](https://github.com/filecoin-project/lotus/blob/v1.25.2/node/impl/full/eth.go#L721-L731) for this in Lotus, the array doesn't start empty, there is an initial element. They have a comment which I don't understand, and conclude that they will duplicate the newest element, but it's unconditional, not just if there is 1 block requested. 

Should we do the same?

**Comment by aakoshh** [comment]
I pushed a commit which tries to fetch the next available base fee to put it into the array at the beginning.

**Comment by snissn** [comment]
@aakoshh  I have tested and can confirm that your latest updates fix the incompatibility with hardhat! The tests run correctly now!

also here is the output from the above eth api call in the newest commit 0f87ed498e6b7b895e1ddac36a20564064fa48c6 

```
response {
  baseFeePerGas: [ '0x3e8', '0x3e8' ],
  gasUsedRatio: [ 0 ],
  oldestBlock: '0x534d7',
  reward: [ [ '0x0' ] ]
}
```

**Review by aakoshh — APPROVED** [review]
It's been tested by Mike, so let's go!

**Pull request merged**
